In [10]:
import pandas as pd

df = pd.read_csv("../data/raw/borough_ptai_2015.csv")
df.head()

  Borough Code          Borough Name  AvPTAI2015 PTAL
0    E09000021  Kingston upon Thames    5.425275    2
1    E09000008               Croydon    6.757744    2
2    E09000006               Bromley    3.592084   1b
3    E09000018              Hounslow    5.842208    2
4    E09000009                Ealing    8.503510    2

In [11]:
df.shape

(33, 4)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Borough Code  33 non-null     object
 1   Borough Name  33 non-null     object
 2   AvPTAI2015    33 non-null     float64
 3   PTAL          33 non-null     object
dtypes: float64(1), object(3)
memory usage: 1.2+ KB

In [13]:
df.describe()

       AvPTAI2015
count   33.000000
mean    14.022116
std     16.178179
min      2.747859
25%      5.542330
50%      8.503510
75%     17.478762
max     90.802508

In [14]:
df.describe(include="object")

       Borough Code          Borough Name PTAL
count            33                    33   33
unique           33                    33    7
top       E09000021  Kingston upon Thames    2
freq              1                     1   13

In [15]:
df.isnull().sum()

Borough Code    0
Borough Name    0
AvPTAI2015      0
PTAL            0
dtype: int64

In [16]:
df.nunique()

Borough Code    33
Borough Name    33
AvPTAI2015      33
PTAL             7
dtype: int64

# PTAL Dataset Assessment

## Dataset Status
Accepted

## Purpose
Provide borough-level transport accessibility as a candidate predictive feature.

## Join Key
Borough Code

## Candidate Features
- AvPTAI2015 (Primary)
- PTAL (Secondary / Under Evaluation)

## Data Quality
- 33 boroughs
- No missing values
- Correct data types
- Ready for integration

In [ ]:
df.to_csv(
    "../data/processed/borough_ptai_2015.csv",
    index=False
)