In [1]:
import pandas as pd

df_crime = pd.read_csv("../data/raw/borough_crime_historical.csv")

In [2]:
df_crime.head()

,Group,SubGroup,BOCU,202007,202008,202009,202010,202011,202012,202101,...,202309,202310,202311,202312,202401,202402,202403,202404,202405,202406
0,ARSON AND CRIMINAL DAMAGE,ARSON,Barking and Dagenham,4,6,2,7,4,2,4,...,4,4,3,4,4,5,6,3,8,2
1,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Barking and Dagenham,122,113,114,120,99,110,100,...,128,82,88,125,126,124,134,112,102,107
2,BURGLARY,BURGLARY BUSINESS AND COMMUNITY,Barking and Dagenham,28,23,32,18,18,24,20,...,38,26,19,20,31,21,30,24,28,33
3,BURGLARY,DOMESTIC BURGLARY,Barking and Dagenham,72,62,55,67,89,92,69,...,0,0,0,0,0,0,0,0,0,0
4,BURGLARY,RES BURGLARY OF A HOME,Barking and Dagenham,0,0,0,0,0,0,0,...,65,47,49,44,57,33,45,42,30,31

In [3]:
df_crime.shape

(1125, 51)

In [4]:
df_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 51 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Group     1125 non-null   object
 1   SubGroup  1125 non-null   object
 2   BOCU      1125 non-null   object
 3   202007    1125 non-null   int64
 4   202008    1125 non-null   int64
 5   202009    1125 non-null   int64
 6   202010    1125 non-null   int64
 7   202011    1125 non-null   int64
 8   202012    1125 non-null   int64
 9   202101    1125 non-null   int64
 10  202102    1125 non-null   int64
 11  202103    1125 non-null   int64
 12  202104    1125 non-null   int64
 13  202105    1125 non-null   int64
 14  202106    1125 non-null   int64
 15  202107    1125 non-null   int64
 16  202108    1125 non-null   int64
 17  202109    1125 non-null   int64
 18  202110    1125 non-null   int64
 19  202111    1125 non-null   int64
 20  202112    1125 non-null   int64
 21  202201    1125 non-null   int64
 22  202202    1125 non-null   int64
 23  202203    1125 non-null   int64
 24  202204    1125 non-null   int64
 25  202205    1125 non-null   int64
 26  202206    1125 non-null   int64
 27  202207    1125 non-null   int64
 28  202208    1125 non-null   int64
 29  202209    1125 non-null   int64
 30  202210    1125 non-null   int64
 31  202211    1125 non-null   int64
 32  202212    1125 non-null   int64
 33  202301    1125 non-null   int64
 34  202302    1125 non-null   int64
 35  202303    1125 non-null   int64
 36  202304    1125 non-null   int64
 37  202305    1125 non-null   int64
 38  202306    1125 non-null   int64
 39  202307    1125 non-null   int64
 40  202308    1125 non-null   int64
 41  202309    1125 non-null   int64
 42  202310    1125 non-null   int64
 43  202311    1125 non-null   int64
 44  202312    1125 non-null   int64
 45  202401    1125 non-null   int64
 46  202402    1125 non-null   int64
 47  202403    1125 non-null   int64
 48  202404    1125 non-null   int64
 49  202405    1125 non-null   int64
 50  202406    1125 non-null   int64
dtypes: int64(48), object(3)
memory usage: 448.4+ KB

In [5]:
df_crime.isnull().sum()

Group       0
SubGroup    0
BOCU        0
202007      0
202008      0
202009      0
202010      0
202011      0
202012      0
202101      0
202102      0
202103      0
202104      0
202105      0
202106      0
202107      0
202108      0
202109      0
202110      0
202111      0
202112      0
202201      0
202202      0
202203      0
202204      0
202205      0
202206      0
202207      0
202208      0
202209      0
202210      0
202211      0
202212      0
202301      0
202302      0
202303      0
202304      0
202305      0
202306      0
202307      0
202308      0
202309      0
202310      0
202311      0
202312      0
202401      0
202402      0
202403      0
202404      0
202405      0
202406      0
dtype: int64

In [6]:
df_crime.nunique()

Group        13
SubGroup     35
BOCU         34
202007      243
202008      250
202009      245
202010      249
202011      236
202012      224
202101      203
202102      208
202103      233
202104      222
202105      237
202106      253
202107      236
202108      239
202109      246
202110      257
202111      252
202112      239
202201      237
202202      230
202203      248
202204      238
202205      256
202206      250
202207      248
202208      252
202209      249
202210      248
202211      247
202212      241
202301      251
202302      241
202303      253
202304      251
202305      264
202306      264
202307      262
202308      253
202309      256
202310      261
202311      259
202312      253
202401      254
202402      247
202403      252
202404      254
202405      261
202406      264
dtype: int64

In [7]:
df_crime.describe()

,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,...,202309,202310,202311,202312,202401,202402,202403,202404,202405,202406
count,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,...,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000
mean,62.618667,62.701333,63.361778,63.427556,57.493333,53.316444,46.883556,46.549333,55.794667,55.069333,...,69.147556,73.360889,70.940444,69.261333,67.229333,66.741333,67.210667,65.974222,70.109333,69.891556
std,80.981037,84.672699,84.253113,84.453768,72.347774,71.393983,60.776029,59.791769,70.663679,70.382538,...,109.669568,133.864639,152.948625,151.662276,125.634365,135.937563,139.590042,127.842904,121.972211,127.709289
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,6.000000,6.000000,5.000000,5.000000,5.000000,6.000000,2.000000,2.000000,2.000000,2.000000
50%,28.000000,26.000000,28.000000,26.000000,25.000000,21.000000,20.000000,20.000000,26.000000,23.000000,...,31.000000,30.000000,29.000000,27.000000,27.000000,28.000000,27.000000,27.000000,29.000000,30.000000
75%,97.000000,95.000000,98.000000,99.000000,92.000000,85.000000,74.000000,73.000000,87.000000,88.000000,...,98.000000,98.000000,93.000000,92.000000,93.000000,85.000000,86.000000,86.000000,91.000000,91.000000
max,715.000000,914.000000,905.000000,915.000000,401.000000,592.000000,303.000000,303.000000,359.000000,449.000000,...,1784.000000,2065.000000,3310.000000,3402.000000,2628.000000,2931.000000,3350.000000,2826.000000,2194.000000,2397.000000

In [8]:
sorted(df_crime["BOCU"].unique())

['Barking and Dagenham',
 'Barnet',
 'Bexley',
 'Brent',
 'Bromley',
 'Camden',
 'Croydon',
 'Ealing',
 'Enfield',
 'Greenwich',
 'Hackney',
 'Hammersmith and Fulham',
 'Haringey',
 'Harrow',
 'Havering',
 'Hillingdon',
 'Hounslow',
 'Islington',
 'Kensington and Chelsea',
 'Kingston upon Thames',
 'Lambeth',
 'Lewisham',
 'London Heathrow and London City Airports',
 'Merton',
 'Newham',
 'Redbridge',
 'Richmond upon Thames',
 'Southwark',
 'Sutton',
 'Tower Hamlets',
 'Unknown',
 'Waltham Forest',
 'Wandsworth',
 'Westminster']

In [9]:
for b in sorted(df_crime["BOCU"].unique()):
    print(b)

Barking and Dagenham
Barnet
Bexley
Brent
Bromley
Camden
Croydon
Ealing
Enfield
Greenwich
Hackney
Hammersmith and Fulham
Haringey
Harrow
Havering
Hillingdon
Hounslow
Islington
Kensington and Chelsea
Kingston upon Thames
Lambeth
Lewisham
London Heathrow and London City Airports
Merton
Newham
Redbridge
Richmond upon Thames
Southwark
Sutton
Tower Hamlets
Unknown
Waltham Forest
Wandsworth
Westminster