# Building the Borough-Year Dataset

# Borough-Year Feature Engineering

This notebook transforms the cleaned London transaction dataset into a borough-year level analytical dataset.

Each row represents one London borough in one calendar year, with aggregated market indicators that will later be used for predictive modelling.

## Workflow

Processed London Transactions

↓

Aggregate by Borough and Year

↓

Create Borough-Year Dataset

↓

Save Processed Dataset

## Output

The processed dataset will be saved as:

`data/processed/borough_year_dataset.csv`

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Project folders

RAW_DATA = Path("../data/raw")
PROCESSED_DATA = Path("../data/processed")

print("Raw folder:", RAW_DATA)
print("Processed folder:", PROCESSED_DATA)

Raw folder: ..\data\raw
Processed folder: ..\data\processed

In [3]:
# Load the processed London dataset

DATA_PATH = PROCESSED_DATA / "london_transactions_2018_2025.csv"

london_transactions = pd.read_csv(DATA_PATH)

print(london_transactions.shape)

(887229, 17)

In [4]:
london_transactions.head()

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,Year
0,{75050A85-94A3-9A88-E053-6B04A8C02390},354000,2018-08-03 00:00,BR6 0TR,T,N,F,8,NaN,COWDEN ROAD,NaN,ORPINGTON,BROMLEY,GREATER LONDON,A,A,2018
1,{75050A85-94A4-9A88-E053-6B04A8C02390},392000,2018-07-27 00:00,KT6 5BH,F,N,L,36,FLAT 2,HOOK ROAD,NaN,SURBITON,KINGSTON UPON THAMES,GREATER LONDON,A,A,2018
2,{75050A85-94A5-9A88-E053-6B04A8C02390},545000,2018-08-24 00:00,SW17 0PS,T,N,F,137,NaN,STRATHDON DRIVE,NaN,LONDON,WANDSWORTH,GREATER LONDON,A,A,2018
3,{75050A85-94A6-9A88-E053-6B04A8C02390},269000,2018-06-29 00:00,BR6 6AX,T,N,F,22,NaN,KINGSLEY ROAD,NaN,ORPINGTON,BROMLEY,GREATER LONDON,A,A,2018
4,{75050A85-94A7-9A88-E053-6B04A8C02390},335000,2018-08-16 00:00,DA7 5QZ,S,N,F,36,NaN,KING HAROLDS WAY,NaN,BEXLEYHEATH,BEXLEY,GREATER LONDON,A,A,2018

In [5]:
london_transactions["District"].nunique()

33

In [6]:
sorted(london_transactions["District"].unique())

['BARKING AND DAGENHAM',
 'BARNET',
 'BEXLEY',
 'BRENT',
 'BROMLEY',
 'CAMDEN',
 'CITY OF LONDON',
 'CITY OF WESTMINSTER',
 'CROYDON',
 'EALING',
 'ENFIELD',
 'GREENWICH',
 'HACKNEY',
 'HAMMERSMITH AND FULHAM',
 'HARINGEY',
 'HARROW',
 'HAVERING',
 'HILLINGDON',
 'HOUNSLOW',
 'ISLINGTON',
 'KENSINGTON AND CHELSEA',
 'KINGSTON UPON THAMES',
 'LAMBETH',
 'LEWISHAM',
 'MERTON',
 'NEWHAM',
 'REDBRIDGE',
 'RICHMOND UPON THAMES',
 'SOUTHWARK',
 'SUTTON',
 'TOWER HAMLETS',
 'WALTHAM FOREST',
 'WANDSWORTH']

In [7]:
borough_year = (
    london_transactions
    .groupby(["District", "Year"])
)

In [8]:
borough_year = (
    london_transactions
    .groupby(["District", "Year"])
    .agg(
        Transactions=("Price", "count"),
        Average_Price=("Price", "mean"),
        Median_Price=("Price", "median"),
        Min_Price=("Price", "min"),
        Max_Price=("Price", "max"),
        Price_STD=("Price", "std")
    )
    .reset_index()
)

In [9]:
borough_year.head()

,District,Year,Transactions,Average_Price,Median_Price,Min_Price,Max_Price,Price_STD
0,BARKING AND DAGENHAM,2018,2404,371419.146007,306750.0,100,20495000,9.097848e+05
1,BARKING AND DAGENHAM,2019,2146,393626.402144,310000.0,100,23160000,1.059141e+06
2,BARKING AND DAGENHAM,2020,1717,468356.971462,320000.0,100,41750000,1.792652e+06
3,BARKING AND DAGENHAM,2021,2537,421573.503745,335000.0,100,50920000,1.783341e+06
4,BARKING AND DAGENHAM,2022,2110,502775.688152,370000.0,100,98800000,2.466056e+06

In [10]:
borough_year.shape

(264, 8)

In [11]:
# Create a working copy for feature engineering

features_df = borough_year.copy()

features_df.head()

,District,Year,Transactions,Average_Price,Median_Price,Min_Price,Max_Price,Price_STD
0,BARKING AND DAGENHAM,2018,2404,371419.146007,306750.0,100,20495000,9.097848e+05
1,BARKING AND DAGENHAM,2019,2146,393626.402144,310000.0,100,23160000,1.059141e+06
2,BARKING AND DAGENHAM,2020,1717,468356.971462,320000.0,100,41750000,1.792652e+06
3,BARKING AND DAGENHAM,2021,2537,421573.503745,335000.0,100,50920000,1.783341e+06
4,BARKING AND DAGENHAM,2022,2110,502775.688152,370000.0,100,98800000,2.466056e+06

In [12]:
features_df = features_df.sort_values(
    by=["District", "Year"]
).reset_index(drop=True)

In [13]:
features_df.head(15)

,District,Year,Transactions,Average_Price,Median_Price,Min_Price,Max_Price,Price_STD
0,BARKING AND DAGENHAM,2018,2404,371419.146007,306750.0,100,20495000,9.097848e+05
1,BARKING AND DAGENHAM,2019,2146,393626.402144,310000.0,100,23160000,1.059141e+06
2,BARKING AND DAGENHAM,2020,1717,468356.971462,320000.0,100,41750000,1.792652e+06
3,BARKING AND DAGENHAM,2021,2537,421573.503745,335000.0,100,50920000,1.783341e+06
4,BARKING AND DAGENHAM,2022,2110,502775.688152,370000.0,100,98800000,2.466056e+06
5,BARKING AND DAGENHAM,2023,1710,437734.550292,374000.0,100,33865422,1.072858e+06
6,BARKING AND DAGENHAM,2024,1743,406767.321859,360000.0,1000,13800000,6.272971e+05
7,BARKING AND DAGENHAM,2025,1735,399006.881268,380000.0,5000,15575000,5.202790e+05
8,BARNET,2018,4837,731702.959892,495000.0,100,67586207,2.038317e+06
9,BARNET,2019,4773,685904.183113,500000.0,100,75450176,1.654520e+06
10,BARNET,2020,4235,719236.872963,530000.0,100,51100000,1.451075e+06
11,BARNET,2021,6292,754072.057851,555000.0,100,55000000,1.368702e+06
12,BARNET,2022,5576,770322.687410,563000.0,100,35100000,1.108924e+06
13,BARNET,2023,4114,798408.821342,540000.0,100,99000000,2.035751e+06
14,BARNET,2024,4528,778356.689488,542500.0,500,37934103,1.330208e+06

## Creating Growth Features

Historical price growth is calculated within each borough.

These features describe how the local housing market has evolved over time and provide temporal information for future prediction tasks.

In [14]:
features_df["Price_Growth"] = (
    features_df
    .groupby("District")["Average_Price"]
    .pct_change()
)

In [15]:
features_df[
    [
        "District",
        "Year",
        "Average_Price",
        "Price_Growth"
    ]
].head(15)

                District  Year  Average_Price  Price_Growth
0   BARKING AND DAGENHAM  2018  371419.146007           NaN
1   BARKING AND DAGENHAM  2019  393626.402144      0.059790
2   BARKING AND DAGENHAM  2020  468356.971462      0.189852
3   BARKING AND DAGENHAM  2021  421573.503745     -0.099888
4   BARKING AND DAGENHAM  2022  502775.688152      0.192617
5   BARKING AND DAGENHAM  2023  437734.550292     -0.129364
6   BARKING AND DAGENHAM  2024  406767.321859     -0.070744
7   BARKING AND DAGENHAM  2025  399006.881268     -0.019078
8                 BARNET  2018  731702.959892           NaN
9                 BARNET  2019  685904.183113     -0.062592
10                BARNET  2020  719236.872963      0.048597
11                BARNET  2021  754072.057851      0.048434
12                BARNET  2022  770322.687410      0.021550
13                BARNET  2023  798408.821342      0.036460
14                BARNET  2024  778356.689488     -0.025115

In [16]:
features_df = features_df.rename(
    columns={
        "Price_Growth": "Average_Price_Growth"
    }
)

In [17]:
features_df.columns

Index(['District', 'Year', 'Transactions', 'Average_Price', 'Median_Price',
       'Min_Price', 'Max_Price', 'Price_STD', 'Average_Price_Growth'],
      dtype='object')

In [18]:
features_df["Median_Price_Growth"] = (
    features_df
    .groupby("District")["Median_Price"]
    .pct_change()
)

In [19]:
features_df[
    [
        "District",
        "Year",
        "Average_Price_Growth",
        "Median_Price_Growth"
    ]
].head(15)

                District  Year  Average_Price_Growth  Median_Price_Growth
0   BARKING AND DAGENHAM  2018                   NaN                  NaN
1   BARKING AND DAGENHAM  2019              0.059790             0.010595
2   BARKING AND DAGENHAM  2020              0.189852             0.032258
3   BARKING AND DAGENHAM  2021             -0.099888             0.046875
4   BARKING AND DAGENHAM  2022              0.192617             0.104478
5   BARKING AND DAGENHAM  2023             -0.129364             0.010811
6   BARKING AND DAGENHAM  2024             -0.070744            -0.037433
7   BARKING AND DAGENHAM  2025             -0.019078             0.055556
8                 BARNET  2018                   NaN                  NaN
9                 BARNET  2019             -0.062592             0.010101
10                BARNET  2020              0.048597             0.060000
11                BARNET  2021              0.048434             0.047170
12                BARNET  2022              0.021550             0.014414
13                BARNET  2023              0.036460            -0.040853
14                BARNET  2024             -0.025115             0.004630

In [20]:
features_df.columns

Index(['District', 'Year', 'Transactions', 'Average_Price', 'Median_Price',
       'Min_Price', 'Max_Price', 'Price_STD', 'Average_Price_Growth',
       'Median_Price_Growth'],
      dtype='object')

## Creating Prediction Targets

Prediction targets are generated by shifting the growth variables one year forward.

This allows each observation to describe the current market while predicting the following year's market performance.

In [21]:
features_df["Target_Average_Price_Growth"] = (
    features_df
    .groupby("District")["Average_Price_Growth"]
    .shift(-1)
)

In [22]:
features_df[
    [
        "District",
        "Year",
        "Average_Price_Growth",
        "Target_Average_Price_Growth"
    ]
].head(15)

,District,Year,Average_Price_Growth,Target_Average_Price_Growth
0,BARKING AND DAGENHAM,2018,NaN,0.059790
1,BARKING AND DAGENHAM,2019,0.059790,0.189852
2,BARKING AND DAGENHAM,2020,0.189852,-0.099888
3,BARKING AND DAGENHAM,2021,-0.099888,0.192617
4,BARKING AND DAGENHAM,2022,0.192617,-0.129364
5,BARKING AND DAGENHAM,2023,-0.129364,-0.070744
6,BARKING AND DAGENHAM,2024,-0.070744,-0.019078
7,BARKING AND DAGENHAM,2025,-0.019078,NaN
8,BARNET,2018,NaN,-0.062592
9,BARNET,2019,-0.062592,0.048597
10,BARNET,2020,0.048597,0.048434
11,BARNET,2021,0.048434,0.021550
12,BARNET,2022,0.021550,0.036460
13,BARNET,2023,0.036460,-0.025115
14,BARNET,2024,-0.025115,-0.083237

In [23]:
features_df["Target_Median_Price_Growth"] = (
    features_df
    .groupby("District")["Median_Price_Growth"]
    .shift(-1)
)

In [24]:
features_df[
    [
        "District",
        "Year",
        "Median_Price_Growth",
        "Target_Median_Price_Growth"
    ]
].head(15)

,District,Year,Median_Price_Growth,Target_Median_Price_Growth
0,BARKING AND DAGENHAM,2018,NaN,0.010595
1,BARKING AND DAGENHAM,2019,0.010595,0.032258
2,BARKING AND DAGENHAM,2020,0.032258,0.046875
3,BARKING AND DAGENHAM,2021,0.046875,0.104478
4,BARKING AND DAGENHAM,2022,0.104478,0.010811
5,BARKING AND DAGENHAM,2023,0.010811,-0.037433
6,BARKING AND DAGENHAM,2024,-0.037433,0.055556
7,BARKING AND DAGENHAM,2025,0.055556,NaN
8,BARNET,2018,NaN,0.010101
9,BARNET,2019,0.010101,0.060000
10,BARNET,2020,0.060000,0.047170
11,BARNET,2021,0.047170,0.014414
12,BARNET,2022,0.014414,-0.040853
13,BARNET,2023,-0.040853,0.004630
14,BARNET,2024,0.004630,0.010783

In [25]:
features_df.head()

,District,Year,Transactions,Average_Price,Median_Price,Min_Price,Max_Price,Price_STD,Average_Price_Growth,Median_Price_Growth,Target_Average_Price_Growth,Target_Median_Price_Growth
0,BARKING AND DAGENHAM,2018,2404,371419.146007,306750.0,100,20495000,9.097848e+05,NaN,NaN,0.059790,0.010595
1,BARKING AND DAGENHAM,2019,2146,393626.402144,310000.0,100,23160000,1.059141e+06,0.059790,0.010595,0.189852,0.032258
2,BARKING AND DAGENHAM,2020,1717,468356.971462,320000.0,100,41750000,1.792652e+06,0.189852,0.032258,-0.099888,0.046875
3,BARKING AND DAGENHAM,2021,2537,421573.503745,335000.0,100,50920000,1.783341e+06,-0.099888,0.046875,0.192617,0.104478
4,BARKING AND DAGENHAM,2022,2110,502775.688152,370000.0,100,98800000,2.466056e+06,0.192617,0.104478,-0.129364,0.010811

In [27]:
features_df.isna().sum()

District                        0
Year                            0
Transactions                    0
Average_Price                   0
Median_Price                    0
Min_Price                       0
Max_Price                       0
Price_STD                       0
Average_Price_Growth           33
Median_Price_Growth            33
Target_Average_Price_Growth    33
Target_Median_Price_Growth     33
dtype: int64

In [28]:
features_df.to_csv(
    PROCESSED_DATA / "borough_year_features.csv",
    index=False
)

print("borough_year_features.csv saved successfully.")

borough_year_features.csv saved successfully.

## Validation Checks

Before using this dataset for predictive modelling, a small set of validation checks is performed to verify that the aggregation, feature engineering and target construction have been completed correctly.

In [29]:
expected_rows = 33 * 8

print("Expected rows:", expected_rows)
print("Actual rows:", len(features_df))

Expected rows: 264
Actual rows: 264

In [30]:
check = london_transactions[
    (london_transactions["District"] == "BARNET") &
    (london_transactions["Year"] == 2024)
]

print("Transactions:", len(check))
print("Average Price:", check["Price"].mean())
print("Median Price:", check["Price"].median())

Transactions: 4528
Average Price: 778356.6894876325
Median Price: 542500.0

In [32]:
features_df[
    (features_df["District"] == "BARNET") &
    (features_df["Year"] == 2024)
]

,District,Year,Transactions,Average_Price,Median_Price,Min_Price,Max_Price,Price_STD,Average_Price_Growth,Median_Price_Growth,Target_Average_Price_Growth,Target_Median_Price_Growth
14,BARNET,2024,4528,778356.689488,542500.0,500,37934103,1.330208e+06,-0.025115,0.00463,-0.083237,0.010783

In [33]:
features_df[
    features_df["District"] == "BARNET"
][
    [
        "Year",
        "Average_Price_Growth",
        "Target_Average_Price_Growth"
    ]
]

    Year  Average_Price_Growth  Target_Average_Price_Growth
8   2018                   NaN                    -0.062592
9   2019             -0.062592                     0.048597
10  2020              0.048597                     0.048434
11  2021              0.048434                     0.021550
12  2022              0.021550                     0.036460
13  2023              0.036460                    -0.025115
14  2024             -0.025115                    -0.083237
15  2025             -0.083237                          NaN

## Validation Summary

Three validation checks were performed before finalising the feature dataset:

- The expected number of borough-year observations was confirmed.
- Aggregated statistics were manually verified against the raw transaction data.
- Prediction targets were validated to ensure correct one-year forward alignment.

The dataset passed all validation checks and is ready for predictive modelling.