# London Property Intelligence

## Notebook 04
### Index of Multiple Deprivation (IMD)

**Objective**

Explore and prepare the IMD dataset for integration into the London Property Intelligence feature store.

In [1]:
import pandas as pd

df_imd = pd.read_excel(
    "../data/raw/ID_2019_for_London.xlsx",
    sheet_name="Borough summary measures",
    header=0
)

In [2]:
print("=" * 60)
print("DATASET SHAPE")
print(df_imd.shape)

print("\n" + "=" * 60)
print("COLUMN NAMES")
print(df_imd.columns.tolist())

print("\n" + "=" * 60)
print("DATA TYPES")
df_imd.info()

print("\n" + "=" * 60)
print("FIRST 5 ROWS")
display(df_imd.head())

============================================================
DATASET SHAPE
(33, 12)

============================================================
COLUMN NAMES
['Local Authority District code (2019)', 'Local Authority District name (2019)', 'IMD - Average rank ', 'IMD - Rank of average rank ', 'IMD - Average score ', 'IMD - Rank of average score ', 'IMD - Proportion of LSOAs in most deprived 10% nationally ', 'IMD - Rank of proportion of LSOAs in most deprived 10% nationally ', 'IMD 2019 - Extent ', 'IMD 2019 - Rank of extent ', 'IMD 2019 - Local concentration ', 'IMD 2019 - Rank of local concentration ']

============================================================
DATA TYPES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 12 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Local Authority District code (2019)                                33 non-null     object
 1   Local Authority District name (2019)                                33 non-null     object
 2   IMD - Average rank                                                  33 non-null     float64
 3   IMD - Rank of average rank                                          33 non-null     int64
 4   IMD - Average score                                                 33 non-null     float64
 5   IMD - Rank of average score                                         33 non-null     int64
 6   IMD - Proportion of LSOAs in most deprived 10% nationally           33 non-null     float64
 7   IMD - Rank of proportion of LSOAs in most deprived 10% nationally   33 non-null     int64
 8   IMD 2019 - Extent                                                   33 non-null     float64
 9   IMD 2019 - Rank of extent                                           33 non-null     int64
 10  IMD 2019 - Local concentration                                      33 non-null     float64
 11  IMD 2019 - Rank of local concentration                              33 non-null     int64
dtypes: float64(5), int64(5), object(2)
memory usage: 3.2+ KB

============================================================
FIRST 5 ROWS

,Local Authority District code (2019),Local Authority District name (2019),IMD - Average rank,IMD - Rank of average rank,IMD - Average score,IMD - Rank of average score,IMD - Proportion of LSOAs in most deprived 10% nationally,IMD - Rank of proportion of LSOAs in most deprived 10% nationally,IMD 2019 - Extent,IMD 2019 - Rank of extent,IMD 2019 - Local concentration,IMD 2019 - Rank of local concentration
0,E09000001,City of London,12420.52,208,14.720,212,0.0000,195,0.0322,220,24167.00,236
1,E09000002,Barking and Dagenham,25551.85,5,32.768,21,0.0364,139,0.4724,20,29391.87,125
2,E09000003,Barnet,13803.35,184,16.148,190,0.0047,193,0.0523,194,26151.40,196
3,E09000004,Bexley,13529.71,190,16.273,187,0.0000,195,0.0755,175,27051.79,179
4,E09000005,Brent,21083.02,49,25.558,79,0.0578,116,0.2074,101,29908.65,114

In [3]:
# Remove extra spaces from column names
df_imd.columns = df_imd.columns.str.strip()

print("Columns cleaned successfully.")

Columns cleaned successfully.

In [4]:
print("=" * 60)
print("MISSING VALUES")
display(df_imd.isnull().sum())

print("\n" + "=" * 60)
print("UNIQUE VALUES")
display(df_imd.nunique())

print("\n" + "=" * 60)
print("SUMMARY STATISTICS")
display(df_imd.describe())

============================================================
MISSING VALUES

Local Authority District code (2019)                                 0
Local Authority District name (2019)                                 0
IMD - Average rank                                                   0
IMD - Rank of average rank                                           0
IMD - Average score                                                  0
IMD - Rank of average score                                          0
IMD - Proportion of LSOAs in most deprived 10% nationally            0
IMD - Rank of proportion of LSOAs in most deprived 10% nationally    0
IMD 2019 - Extent                                                    0
IMD 2019 - Rank of extent                                            0
IMD 2019 - Local concentration                                       0
IMD 2019 - Rank of local concentration                               0
dtype: int64

============================================================
UNIQUE VALUES

Local Authority District code (2019)                                 33
Local Authority District name (2019)                                 33
IMD - Average rank                                                   33
IMD - Rank of average rank                                           33
IMD - Average score                                                  33
IMD - Rank of average score                                          33
IMD - Proportion of LSOAs in most deprived 10% nationally            23
IMD - Rank of proportion of LSOAs in most deprived 10% nationally    23
IMD 2019 - Extent                                                    33
IMD 2019 - Rank of extent                                            33
IMD 2019 - Local concentration                                       33
IMD 2019 - Rank of local concentration                               33
dtype: int64

============================================================
SUMMARY STATISTICS

,IMD - Average rank,IMD - Rank of average rank,IMD - Average score,IMD - Rank of average score,IMD - Proportion of LSOAs in most deprived 10% nationally,IMD - Rank of proportion of LSOAs in most deprived 10% nationally,IMD 2019 - Extent,IMD 2019 - Rank of extent,IMD 2019 - Local concentration,IMD 2019 - Rank of local concentration
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,17514.279091,118.181818,21.294667,131.545455,0.021976,166.272727,0.162491,137.909091,27563.435455,164.757576
std,4745.933927,82.861879,6.073203,73.229985,0.029696,36.010652,0.120208,66.653659,2434.135251,46.229746
min,7159.190000,5.000000,9.425000,21.000000,0.000000,78.000000,0.007600,20.000000,20278.670000,97.000000
25%,13803.350000,43.000000,16.273000,74.000000,0.000000,148.000000,0.058200,91.000000,26225.860000,133.000000
50%,18371.230000,102.000000,21.526000,121.000000,0.008300,188.000000,0.163000,127.000000,28576.650000,152.000000
75%,21247.360000,184.000000,25.781000,187.000000,0.029600,195.000000,0.230500,186.000000,29186.800000,194.000000
max,25551.850000,297.000000,32.768000,295.000000,0.111100,195.000000,0.472400,273.000000,30429.890000,285.000000

In [5]:
display(

    df_imd
    .sort_values(
        by="IMD - Average score",
        ascending=False
    )[[
        "Local Authority District name (2019)",
        "IMD - Average score"
    ]]
    .head(33)

)

   Local Authority District name (2019)  IMD - Average score
1                  Barking and Dagenham               32.768
11                              Hackney               32.526
24                               Newham               29.577
13                             Haringey               27.956
29                        Tower Hamlets               27.913
18                            Islington               27.535
22                             Lewisham               26.661
27                            Southwark               25.811
9                               Enfield               25.781
4                                 Brent               25.558
21                              Lambeth               25.422
30                       Waltham Forest               25.209
10                            Greenwich               24.464
8                                Ealing               22.710
7                               Croydon               22.477
12               Hammersmith and Fulham               22.270
19               Kensington and Chelsea               21.526
17                             Hounslow               21.487
32                          Westminster               20.339
6                                Camden               20.131
16                           Hillingdon               18.223
25                            Redbridge               17.203
15                             Havering               16.789
31                           Wandsworth               16.611
3                                Bexley               16.273
2                                Barnet               16.148
14                               Harrow               15.031
0                        City of London               14.720
23                               Merton               14.649
5                               Bromley               14.163
28                               Sutton               13.987
20                 Kingston upon Thames               11.381
26                 Richmond upon Thames                9.425

## Findings

- Dataset contains all 33 London Boroughs.
- No missing values.
- Dataset quality is excellent.
- Ready for feature engineering.