# Population Dataset (ONS)

Dataset:
Mid-Year Population Estimates (ONS)

Purpose:
Explore and prepare borough-level population data for Version 3.

In [2]:
from pathlib import Path
import pandas as pd

In [3]:
# Project folders

RAW_DATA = Path("../data/raw")
PROCESSED_DATA = Path("../data/processed")

print("Raw folder:", RAW_DATA)
print("Processed folder:", PROCESSED_DATA)

Raw folder: ..\data\raw
Processed folder: ..\data\processed

In [4]:
# Load MYE4 sheet from ONS population workbook
# This sheet will be audited before deciding whether it becomes
# the population layer for the London Intelligence Dataset.

population_raw = pd.read_excel(
    RAW_DATA / "ons_population_2022.xlsx",
    sheet_name="MYE4",
    header=None
)

population_raw.shape

(381, 15)

In [5]:
population_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,MYE4: Population estimates: Summary for Englan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains one table. Freeze pane...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,To turn off freeze panes select the 'View' rib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Please choose from the links presented in the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"This met my needs, please produce it next year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,I need something slightly different (please sp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,This is not what I need at all (please specify),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Code,Name,Geography,Mid-2022,Mid-2021,Mid-2020,Mid-2019,Mid-2018,Mid-2017,Mid-2016,Mid-2015,Mid-2014,Mid-2013,Mid-2012,Mid-2011
8,K04000001,ENGLAND AND WALES,Country,60245218,59660524,59430444,59317788,59008368,58700914,58366199,57881415,57444107,56989744,56577740,56170927
9,E92000001,ENGLAND,Country,57112542,56554891,56325961,56230056,55924528,55619548,55289034,54808676,54370319,53918686,53506812,53107169
10,E12000001,NORTH EAST,Region,2682069,2647493,2637426,2636676,2629393,2623787,2618253,2611804,2610482,2603299,2598972,2596441
11,E06000047,County Durham,Unitary Authority,527704,521447,519204,518562,516648,515911,514431,513924,513604,513179,513122,512994
12,E06000005,Darlington,Unitary Authority,109413,108210,106827,106532,106411,106541,106258,105988,105825,105591,105557,105584
13,E06000001,Hartlepool,Unitary Authority,93847,92575,92202,92401,92288,92306,92260,92125,92358,92465,92344,92088
14,E06000002,Middlesbrough,Unitary Authority,148583,143943,142459,142134,141057,141213,140649,139602,139030,138588,138472,138368

In [6]:
population_raw.tail(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
366,W06000008,Ceredigion,Unitary Authority,71873,70676,71421,70639,71291,72220,72900,73724,75197,76087,76215,75293
367,W06000009,Pembrokeshire,Unitary Authority,124365,123633,122572,121432,121194,121382,121438,121721,122148,122302,122621,122613
368,W06000010,Carmarthenshire,Unitary Authority,189148,188172,187391,186125,185444,184984,184985,184404,184349,184252,184206,183961
369,W06000011,Swansea,Unitary Authority,242039,237897,238992,238707,239184,239266,239300,239354,239228,239237,239197,238691
370,W06000012,Neath Port Talbot,Unitary Authority,142204,141934,142308,141385,141342,141022,141000,139704,139439,139093,139694,139880
371,W06000013,Bridgend,Unitary Authority,146135,145738,145434,144500,143583,143355,142887,142177,141333,140579,139985,139410
372,W06000014,Vale of Glamorgan,Unitary Authority,133619,132491,131224,129802,129165,128377,127082,126261,126714,126458,126703,126679
373,W06000015,Cardiff,Unitary Authority,371104,359824,360287,357137,355125,354348,352982,351600,350949,349982,348084,345442
374,W06000016,Rhondda Cynon Taf,Unitary Authority,239235,237545,238039,237574,236685,236357,235567,235233,235284,235145,235271,234373
375,W06000024,Merthyr Tydfil,Unitary Authority,58881,58869,59194,59255,59349,59337,59247,58922,58859,58791,58869,58851
376,W06000018,Caerphilly,Unitary Authority,176131,175999,176805,176735,177277,177610,178013,178269,178513,178236,178563,178782
377,W06000019,Blaenau Gwent,Unitary Authority,66960,66989,67219,67382,67566,67829,68135,68395,68737,69186,69589,69812
378,W06000020,Torfaen,Unitary Authority,92863,92454,92337,91685,91130,90638,90730,90844,90866,90842,91199,91190
379,W06000021,Monmouthshire,Unitary Authority,93985,93163,92456,91730,91834,91791,92024,91867,91864,91822,91623,91508
380,W06000022,Newport,Unitary Authority,161565,159687,158438,156773,155222,153234,150926,148948,148150,147586,146760,145785

In [7]:
# Load the actual MYE4 table
# Skip metadata rows and use the real table header

population_df = pd.read_excel(
    RAW_DATA / "ons_population_2022.xlsx",
    sheet_name="MYE4",
    header=7
)

population_df.head()

,Code,Name,Geography,Mid-2022,Mid-2021,Mid-2020,Mid-2019,Mid-2018,Mid-2017,Mid-2016,Mid-2015,Mid-2014,Mid-2013,Mid-2012,Mid-2011
0,K04000001,ENGLAND AND WALES,Country,60245218,59660524,59430444,59317788,59008368,58700914,58366199,57881415,57444107,56989744,56577740,56170927
1,E92000001,ENGLAND,Country,57112542,56554891,56325961,56230056,55924528,55619548,55289034,54808676,54370319,53918686,53506812,53107169
2,E12000001,NORTH EAST,Region,2682069,2647493,2637426,2636676,2629393,2623787,2618253,2611804,2610482,2603299,2598972,2596441
3,E06000047,County Durham,Unitary Authority,527704,521447,519204,518562,516648,515911,514431,513924,513604,513179,513122,512994
4,E06000005,Darlington,Unitary Authority,109413,108210,106827,106532,106411,106541,106258,105988,105825,105591,105557,105584

In [8]:
print("=" * 60)
print("MYE4 POPULATION DATASET AUDIT")
print("=" * 60)

print(f"Dataset shape: {population_df.shape}")

print("\nColumns:")
print(population_df.columns.tolist())

print("\nData types:")
print(population_df.dtypes)

print("\nMissing values:")
print(population_df.isna().sum())

print("\nGeography types:")
print(population_df["Geography"].value_counts())

print("\nNumber of areas:")
print(population_df["Name"].nunique())

print("\nDuplicate area-year check:")
print(
    population_df.duplicated(
        subset=["Code", "Name"]
    ).sum()
)

============================================================
MYE4 POPULATION DATASET AUDIT
============================================================
Dataset shape: (373, 15)

Columns:
['Code', 'Name', 'Geography', 'Mid-2022', 'Mid-2021', 'Mid-2020', 'Mid-2019', 'Mid-2018', 'Mid-2017', 'Mid-2016', 'Mid-2015', 'Mid-2014', 'Mid-2013', 'Mid-2012', 'Mid-2011']

Data types:
Code         object
Name         object
Geography    object
Mid-2022      int64
Mid-2021      int64
Mid-2020      int64
Mid-2019      int64
Mid-2018      int64
Mid-2017      int64
Mid-2016      int64
Mid-2015      int64
Mid-2014      int64
Mid-2013      int64
Mid-2012      int64
Mid-2011      int64
dtype: object

Missing values:
Code         0
Name         0
Geography    0
Mid-2022     0
Mid-2021     0
Mid-2020     0
Mid-2019     0
Mid-2018     0
Mid-2017     0
Mid-2016     0
Mid-2015     0
Mid-2014     0
Mid-2013     0
Mid-2012     0
Mid-2011     0
dtype: int64

Geography types:
Geography
Non-metropolitan District    181
Unitary Authority             81
Metropolitan District         36
London Borough                33
County                        24
Region                         9
Metropolitan County            6
Country                        3
Name: count, dtype: int64

Number of areas:
373

Duplicate area-year check:
0

## Convert Population Dataset from Wide Format to Long Format

The original MYE4 population dataset stores each year as a separate column.
This step reshapes the dataset into a time-series format where each row represents
one borough-area observation for one year.

This structure will make the population layer compatible with the borough-year
property dataset and future data integration steps.

In [9]:
population_long = population_df.melt(
    id_vars=[
        "Code",
        "Name",
        "Geography"
    ],
    var_name="Year",
    value_name="Population"
)

population_long.head()

        Code               Name          Geography      Year  Population
0  K04000001  ENGLAND AND WALES            Country  Mid-2022    60245218
1  E92000001            ENGLAND            Country  Mid-2022    57112542
2  E12000001         NORTH EAST             Region  Mid-2022     2682069
3  E06000047      County Durham  Unitary Authority  Mid-2022      527704
4  E06000005         Darlington  Unitary Authority  Mid-2022      109413

## Reshape Population Data

Convert the ONS population dataset from wide format (years as columns)
into long format (one row per area-year observation).

This structure makes the dataset compatible with time-based analysis
and future merging with the borough-year property dataset.

In [10]:
population_long = population_df.melt(
    id_vars=[
        "Code",
        "Name",
        "Geography"
    ],
    var_name="Year",
    value_name="Population"
)

population_long.head()

        Code               Name          Geography      Year  Population
0  K04000001  ENGLAND AND WALES            Country  Mid-2022    60245218
1  E92000001            ENGLAND            Country  Mid-2022    57112542
2  E12000001         NORTH EAST             Region  Mid-2022     2682069
3  E06000047      County Durham  Unitary Authority  Mid-2022      527704
4  E06000005         Darlington  Unitary Authority  Mid-2022      109413

## Verify Year Column

Check that the Year column is already in numeric format and ready
for time-based analysis.

In [11]:
print(population_long["Year"].dtype)

print(sorted(population_long["Year"].unique()))

object
['Mid-2011', 'Mid-2012', 'Mid-2013', 'Mid-2014', 'Mid-2015', 'Mid-2016', 'Mid-2017', 'Mid-2018', 'Mid-2019', 'Mid-2020', 'Mid-2021', 'Mid-2022']

## Check Geographic Levels

Review the geographic categories available in the ONS population dataset
before filtering London boroughs.

In [12]:
population_long["Geography"].value_counts()

Geography
Non-metropolitan District    2172
Unitary Authority             972
Metropolitan District         432
London Borough                396
County                        288
Region                        108
Metropolitan County            72
Country                        36
Name: count, dtype: int64

## Filter London Boroughs

Select only London Borough observations from the ONS population dataset.

This creates the population layer required for integration with the
borough-year property dataset.

In [13]:
london_population = population_long[
    population_long["Geography"] == "London Borough"
].copy()

london_population.head()

          Code                    Name       Geography      Year  Population
212  E09000007                  Camden  London Borough  Mid-2022      217365
213  E09000001          City of London  London Borough  Mid-2022       11457
214  E09000012                 Hackney  London Borough  Mid-2022      261632
215  E09000013  Hammersmith and Fulham  London Borough  Mid-2022      185506
216  E09000014                Haringey  London Borough  Mid-2022      262413

In [14]:
london_population.shape

(396, 5)

In [15]:
london_population["Name"].nunique()

33

In [16]:
sorted(london_population["Year"].unique())

['Mid-2011',
 'Mid-2012',
 'Mid-2013',
 'Mid-2014',
 'Mid-2015',
 'Mid-2016',
 'Mid-2017',
 'Mid-2018',
 'Mid-2019',
 'Mid-2020',
 'Mid-2021',
 'Mid-2022']

In [17]:
print(london_population["Year"].dtype)

object

## Clean Year Column

The Year column contains labels from the original ONS workbook
(e.g. "Mid-2022"). This step extracts the numeric year value
to make the population dataset compatible with other time-based datasets.

In [18]:
london_population["Year"] = (
    london_population["Year"]
    .str.replace("Mid-", "", regex=False)
    .astype(int)
)

london_population.head()

          Code                    Name       Geography  Year  Population
212  E09000007                  Camden  London Borough  2022      217365
213  E09000001          City of London  London Borough  2022       11457
214  E09000012                 Hackney  London Borough  2022      261632
215  E09000013  Hammersmith and Fulham  London Borough  2022      185506
216  E09000014                Haringey  London Borough  2022      262413

## Population Layer Validation

Validate the cleaned London population dataset before integrating it
into the London Intelligence Dataset.

In [19]:
print("=" * 60)
print("LONDON POPULATION LAYER AUDIT")
print("=" * 60)

print(f"Dataset shape: {london_population.shape}")

print(f"\nNumber of boroughs: {london_population['Name'].nunique()}")

print(
    f"Years covered: "
    f"{sorted(london_population['Year'].astype(int).unique().tolist())}"
)

print(
    f"Duplicate Borough-Year pairs: "
    f"{london_population.duplicated(subset=['Name', 'Year']).sum()}"
)

print("\nMissing values:")
print(london_population.isna().sum())

============================================================
LONDON POPULATION LAYER AUDIT
============================================================
Dataset shape: (396, 5)

Number of boroughs: 33
Years covered: [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
Duplicate Borough-Year pairs: 0

Missing values:
Code          0
Name          0
Geography     0
Year          0
Population    0
dtype: int64

In [20]:
OUTPUT_FILE = PROCESSED_DATA / "london_population.csv"

london_population.to_csv(
    OUTPUT_FILE,
    index=False
)

print("Saved to:", OUTPUT_FILE)

Saved to: ..\data\processed\london_population.csv

In [21]:
saved_df = pd.read_csv(OUTPUT_FILE)

print(saved_df.shape)

saved_df.head()

(396, 5)

        Code                    Name       Geography  Year  Population
0  E09000007                  Camden  London Borough  2022      217365
1  E09000001          City of London  London Borough  2022       11457
2  E09000012                 Hackney  London Borough  2022      261632
3  E09000013  Hammersmith and Fulham  London Borough  2022      185506
4  E09000014                Haringey  London Borough  2022      262413

In [22]:
saved_population = pd.read_csv(OUTPUT_FILE)

print(saved_population.shape)

saved_population.head()

(396, 5)

        Code                    Name       Geography  Year  Population
0  E09000007                  Camden  London Borough  2022      217365
1  E09000001          City of London  London Borough  2022       11457
2  E09000012                 Hackney  London Borough  2022      261632
3  E09000013  Hammersmith and Fulham  London Borough  2022      185506
4  E09000014                Haringey  London Borough  2022      262413