# Population Dataset (ONS)

Dataset:
Mid-Year Population Estimates (ONS)

Purpose:
Explore and prepare borough-level population data for Version 3.

In [194]:
from pathlib import Path
import pandas as pd

In [195]:
# Project folders

RAW_DATA = Path("../data/raw")
PROCESSED_DATA = Path("../data/processed")

print("Raw folder:", RAW_DATA)
print("Processed folder:", PROCESSED_DATA)

Raw folder: ..\data\raw
Processed folder: ..\data\processed

In [196]:
# Load MYE4 sheet from ONS population workbook
# This sheet will be audited before deciding whether it becomes
# the population layer for the London Intelligence Dataset.

population_raw = pd.read_excel(
    RAW_DATA / "ons_population_2022.xlsx",
    sheet_name="MYE4",
    header=None
)

population_raw.shape

(381, 15)

In [288]:
population_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,MYE4: Population estimates: Summary for Englan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains one table. Freeze pane...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,To turn off freeze panes select the 'View' rib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Please choose from the links presented in the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"This met my needs, please produce it next year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,I need something slightly different (please sp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,This is not what I need at all (please specify),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Code,Name,Geography,Mid-2022,Mid-2021,Mid-2020,Mid-2019,Mid-2018,Mid-2017,Mid-2016,Mid-2015,Mid-2014,Mid-2013,Mid-2012,Mid-2011
8,K04000001,ENGLAND AND WALES,Country,60245218,59660524,59430444,59317788,59008368,58700914,58366199,57881415,57444107,56989744,56577740,56170927
9,E92000001,ENGLAND,Country,57112542,56554891,56325961,56230056,55924528,55619548,55289034,54808676,54370319,53918686,53506812,53107169
10,E12000001,NORTH EAST,Region,2682069,2647493,2637426,2636676,2629393,2623787,2618253,2611804,2610482,2603299,2598972,2596441
11,E06000047,County Durham,Unitary Authority,527704,521447,519204,518562,516648,515911,514431,513924,513604,513179,513122,512994
12,E06000005,Darlington,Unitary Authority,109413,108210,106827,106532,106411,106541,106258,105988,105825,105591,105557,105584
13,E06000001,Hartlepool,Unitary Authority,93847,92575,92202,92401,92288,92306,92260,92125,92358,92465,92344,92088
14,E06000002,Middlesbrough,Unitary Authority,148583,143943,142459,142134,141057,141213,140649,139602,139030,138588,138472,138368

In [334]:
population_raw.tail(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
366,W06000008,Ceredigion,Unitary Authority,71873,70676,71421,70639,71291,72220,72900,73724,75197,76087,76215,75293
367,W06000009,Pembrokeshire,Unitary Authority,124365,123633,122572,121432,121194,121382,121438,121721,122148,122302,122621,122613
368,W06000010,Carmarthenshire,Unitary Authority,189148,188172,187391,186125,185444,184984,184985,184404,184349,184252,184206,183961
369,W06000011,Swansea,Unitary Authority,242039,237897,238992,238707,239184,239266,239300,239354,239228,239237,239197,238691
370,W06000012,Neath Port Talbot,Unitary Authority,142204,141934,142308,141385,141342,141022,141000,139704,139439,139093,139694,139880
371,W06000013,Bridgend,Unitary Authority,146135,145738,145434,144500,143583,143355,142887,142177,141333,140579,139985,139410
372,W06000014,Vale of Glamorgan,Unitary Authority,133619,132491,131224,129802,129165,128377,127082,126261,126714,126458,126703,126679
373,W06000015,Cardiff,Unitary Authority,371104,359824,360287,357137,355125,354348,352982,351600,350949,349982,348084,345442
374,W06000016,Rhondda Cynon Taf,Unitary Authority,239235,237545,238039,237574,236685,236357,235567,235233,235284,235145,235271,234373
375,W06000024,Merthyr Tydfil,Unitary Authority,58881,58869,59194,59255,59349,59337,59247,58922,58859,58791,58869,58851
376,W06000018,Caerphilly,Unitary Authority,176131,175999,176805,176735,177277,177610,178013,178269,178513,178236,178563,178782
377,W06000019,Blaenau Gwent,Unitary Authority,66960,66989,67219,67382,67566,67829,68135,68395,68737,69186,69589,69812
378,W06000020,Torfaen,Unitary Authority,92863,92454,92337,91685,91130,90638,90730,90844,90866,90842,91199,91190
379,W06000021,Monmouthshire,Unitary Authority,93985,93163,92456,91730,91834,91791,92024,91867,91864,91822,91623,91508
380,W06000022,Newport,Unitary Authority,161565,159687,158438,156773,155222,153234,150926,148948,148150,147586,146760,145785

In [380]:
# Load the actual MYE4 table
# Skip metadata rows and use the real table header

population_df = pd.read_excel(
    RAW_DATA / "ons_population_2022.xlsx",
    sheet_name="MYE4",
    header=7
)

population_df.head()

,Code,Name,Geography,Mid-2022,Mid-2021,Mid-2020,Mid-2019,Mid-2018,Mid-2017,Mid-2016,Mid-2015,Mid-2014,Mid-2013,Mid-2012,Mid-2011
0,K04000001,ENGLAND AND WALES,Country,60245218,59660524,59430444,59317788,59008368,58700914,58366199,57881415,57444107,56989744,56577740,56170927
1,E92000001,ENGLAND,Country,57112542,56554891,56325961,56230056,55924528,55619548,55289034,54808676,54370319,53918686,53506812,53107169
2,E12000001,NORTH EAST,Region,2682069,2647493,2637426,2636676,2629393,2623787,2618253,2611804,2610482,2603299,2598972,2596441
3,E06000047,County Durham,Unitary Authority,527704,521447,519204,518562,516648,515911,514431,513924,513604,513179,513122,512994
4,E06000005,Darlington,Unitary Authority,109413,108210,106827,106532,106411,106541,106258,105988,105825,105591,105557,105584

In [426]:
print("=" * 60)
print("MYE4 POPULATION DATASET AUDIT")
print("=" * 60)

print(f"Dataset shape: {population_df.shape}")

print("\nColumns:")
print(population_df.columns.tolist())

print("\nData types:")
print(population_df.dtypes)

print("\nMissing values:")
print(population_df.isna().sum())

print("\nGeography types:")
print(population_df["Geography"].value_counts())

print("\nNumber of areas:")
print(population_df["Name"].nunique())

print("\nDuplicate area-year check:")
print(
    population_df.duplicated(
        subset=["Code", "Name"]
    ).sum()
)

============================================================
MYE4 POPULATION DATASET AUDIT
============================================================
Dataset shape: (373, 15)

Columns:
['Code', 'Name', 'Geography', 'Mid-2022', 'Mid-2021', 'Mid-2020', 'Mid-2019', 'Mid-2018', 'Mid-2017', 'Mid-2016', 'Mid-2015', 'Mid-2014', 'Mid-2013', 'Mid-2012', 'Mid-2011']

Data types:
Code         object
Name         object
Geography    object
Mid-2022      int64
Mid-2021      int64
Mid-2020      int64
Mid-2019      int64
Mid-2018      int64
Mid-2017      int64
Mid-2016      int64
Mid-2015      int64
Mid-2014      int64
Mid-2013      int64
Mid-2012      int64
Mid-2011      int64
dtype: object

Missing values:
Code         0
Name         0
Geography    0
Mid-2022     0
Mid-2021     0
Mid-2020     0
Mid-2019     0
Mid-2018     0
Mid-2017     0
Mid-2016     0
Mid-2015     0
Mid-2014     0
Mid-2013     0
Mid-2012     0
Mid-2011     0
dtype: int64

Geography types:
Geography
Non-metropolitan District    181
Unitary Authority             81
Metropolitan District         36
London Borough                33
County                        24
Region                         9
Metropolitan County            6
Country                        3
Name: count, dtype: int64

Number of areas:
373

Duplicate area-year check:
0

## Convert Population Dataset from Wide Format to Long Format

The original MYE4 population dataset stores each year as a separate column.
This step reshapes the dataset into a time-series format where each row represents
one borough-area observation for one year.

This structure will make the population layer compatible with the borough-year
property dataset and future data integration steps.

In [472]:
population_long = population_df.melt(
    id_vars=[
        "Code",
        "Name",
        "Geography"
    ],
    var_name="Year",
    value_name="Population"
)

population_long.head()

        Code               Name          Geography      Year  Population
0  K04000001  ENGLAND AND WALES            Country  Mid-2022    60245218
1  E92000001            ENGLAND            Country  Mid-2022    57112542
2  E12000001         NORTH EAST             Region  Mid-2022     2682069
3  E06000047      County Durham  Unitary Authority  Mid-2022      527704
4  E06000005         Darlington  Unitary Authority  Mid-2022      109413

## Reshape Population Data

Convert the ONS population dataset from wide format (years as columns)
into long format (one row per area-year observation).

This structure makes the dataset compatible with time-based analysis
and future merging with the borough-year property dataset.

In [614]:
population_long = population_df.melt(
    id_vars=[
        "Code",
        "Name",
        "Geography"
    ],
    var_name="Year",
    value_name="Population"
)

population_long.head()

        Code               Name          Geography      Year  Population
0  K04000001  ENGLAND AND WALES            Country  Mid-2022    60245218
1  E92000001            ENGLAND            Country  Mid-2022    57112542
2  E12000001         NORTH EAST             Region  Mid-2022     2682069
3  E06000047      County Durham  Unitary Authority  Mid-2022      527704
4  E06000005         Darlington  Unitary Authority  Mid-2022      109413

## Verify Year Column

Check that the Year column is already in numeric format and ready
for time-based analysis.

In [664]:
print(population_long["Year"].dtype)

print(sorted(population_long["Year"].unique()))

int64
[np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022)]

## Check Geographic Levels

Review the geographic categories available in the ONS population dataset
before filtering London boroughs.

In [712]:
population_long["Geography"].value_counts()

Geography
Non-metropolitan District    2172
Unitary Authority             972
Metropolitan District         432
London Borough                396
County                        288
Region                        108
Metropolitan County            72
Country                        36
Name: count, dtype: int64

## Filter London Boroughs

Select only London Borough observations from the ONS population dataset.

This creates the population layer required for integration with the
borough-year property dataset.

In [758]:
london_population = population_long[
    population_long["Geography"] == "London Borough"
].copy()

london_population.head()

          Code                    Name       Geography      Year  Population
212  E09000007                  Camden  London Borough  Mid-2022      217365
213  E09000001          City of London  London Borough  Mid-2022       11457
214  E09000012                 Hackney  London Borough  Mid-2022      261632
215  E09000013  Hammersmith and Fulham  London Borough  Mid-2022      185506
216  E09000014                Haringey  London Borough  Mid-2022      262413

In [804]:
london_population.shape

(396, 5)

In [850]:
london_population["Name"].nunique()

33

In [896]:
sorted(london_population["Year"].unique())

['Mid-2011',
 'Mid-2012',
 'Mid-2013',
 'Mid-2014',
 'Mid-2015',
 'Mid-2016',
 'Mid-2017',
 'Mid-2018',
 'Mid-2019',
 'Mid-2020',
 'Mid-2021',
 'Mid-2022']

In [988]:
print(london_population["Year"].dtype)

object

## Clean Year Column

The Year column contains labels from the original ONS workbook
(e.g. "Mid-2022"). This step extracts the numeric year value
to make the population dataset compatible with other time-based datasets.

In [1034]:
london_population["Year"] = (
    london_population["Year"]
    .str.replace("Mid-", "", regex=False)
    .astype(int)
)

london_population.head()

          Code                    Name       Geography  Year  Population
212  E09000007                  Camden  London Borough  2022      217365
213  E09000001          City of London  London Borough  2022       11457
214  E09000012                 Hackney  London Borough  2022      261632
215  E09000013  Hammersmith and Fulham  London Borough  2022      185506
216  E09000014                Haringey  London Borough  2022      262413

## Population Layer Validation

Validate the cleaned London population dataset before integrating it
into the London Intelligence Dataset.

In [1035]:
excel = pd.ExcelFile("../data/raw/ons_population_2022.xlsx")
excel.sheet_names

['Cover sheet',
 'Contents',
 'Notes',
 'Geography guide',
 'Related publications',
 'MYE1',
 'MYE2 - Persons',
 'MYE2 - Females',
 'MYE2 - Males',
 'MYE3',
 'MYE4',
 'MYE5',
 'MYE6']

In [1036]:
df_population = pd.read_excel(
    "../data/raw/ons_population_2022.xlsx",
    sheet_name="MYE2 - Persons"
)

df_population.head()

,"MYE2: Persons by single year of age and sex for local authorities in England and Wales, mid-2022",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,This worksheet contains one table. Freeze pane...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,To turn off freeze panes select the 'View' rib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Please choose from the links presented in the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"This met my needs, please produce it next year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I need something slightly different (please sp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1037]:
df_population.shape

(380, 95)

In [1038]:
df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 95 columns):
 #   Column                                                                                            Non-Null Count  Dtype
---  ------                                                                                            --------------  -----
 0   MYE2: Persons by single year of age and sex for local authorities in England and Wales, mid-2022  380 non-null    object
 1   Unnamed: 1                                                                                        374 non-null    object
 2   Unnamed: 2                                                                                        374 non-null    object
 3   Unnamed: 3                                                                                        374 non-null    object
 4   Unnamed: 4                                                                                        374 non-null    float64
 5   Unnamed: 5                                                                                        374 non-null    float64
 6   Unnamed: 6                                                                                        374 non-null    float64
 7   Unnamed: 7                                                                                        374 non-null    float64
 8   Unnamed: 8                                                                                        374 non-null    float64
 9   Unnamed: 9                                                                                        374 non-null    float64
 10  Unnamed: 10                                                                                       374 non-null    float64
 11  Unnamed: 11                                                                                       374 non-null    float64
 12  Unnamed: 12                                                                                       374 non-null    float64
 13  Unnamed: 13                                                                                       374 non-null    float64
 14  Unnamed: 14                                                                                       374 non-null    float64
 15  Unnamed: 15                                                                                       374 non-null    float64
 16  Unnamed: 16                                                                                       374 non-null    float64
 17  Unnamed: 17                                                                                       374 non-null    float64
 18  Unnamed: 18                                                                                       374 non-null    float64
 19  Unnamed: 19                                                                                       374 non-null    float64
 20  Unnamed: 20                                                                                       374 non-null    float64
 21  Unnamed: 21                                                                                       374 non-null    float64
 22  Unnamed: 22                                                                                       374 non-null    float64
 23  Unnamed: 23                                                                                       374 non-null    float64
 24  Unnamed: 24                                                                                       374 non-null    float64
 25  Unnamed: 25                                                                                       374 non-null    float64
 26  Unnamed: 26                                                                                       374 non-null    float64
 27  Unnamed: 27                                                                                       374 non-null    float64
 28  Unnamed: 28                                                                                       374 non-null    float64
 29  Unnamed: 29                                                                                       374 non-null    float64
 30  Unnamed: 30                                                                                       374 non-null    float64
 31  Unnamed: 31                                                                                       374 non-null    float64
 32  Unnamed: 32                                                                                       374 non-null    float64
 33  Unnamed: 33                                                                                       374 non-null    float64
 34  Unnamed: 34                                                                                       374 non-null    float64
 35  Unnamed: 35                                                                                       374 non-null    float64
 36  Unnamed: 36                                                                                       374 non-null    float64
 37  Unnamed: 37                                                                                       374 non-null    float64
 38  Unnamed: 38                                                                                       374 non-null    float64
 39  Unnamed: 39                                                                                       374 non-null    float64
 40  Unnamed: 40                                                                                       374 non-null    float64
 41  Unnamed: 41                                                                                       374 non-null    float64
 42  Unnamed: 42                                                                                       374 non-null    float64
 43  Unnamed: 43                                                                                       374 non-null    float64
 44  Unnamed: 44                                                                                       374 non-null    float64
 45  Unnamed: 45                                                                                       374 non-null    float64
 46  Unnamed: 46                                                                                       374 non-null    float64
 47  Unnamed: 47                                                                                       374 non-null    float64
 48  Unnamed: 48                                                                                       374 non-null    float64
 49  Unnamed: 49                                                                                       374 non-null    float64
 50  Unnamed: 50                                                                                       374 non-null    float64
 51  Unnamed: 51                                                                                       374 non-null    float64
 52  Unnamed: 52                                                                                       374 non-null    float64
 53  Unnamed: 53                                                                                       374 non-null    float64
 54  Unnamed: 54                                                                                       374 non-null    float64
 55  Unnamed: 55                                                                                       374 non-null    float64
 56  Unnamed: 56                                                                                       374 non-null    float64
 57  Unnamed: 57                                                                                       374 non-null    float64
 58  Unnamed: 58                                                                                       374 non-null    float64
 59  Unnamed: 59                                                                                       374 non-null    float64
 60  Unnamed: 60                                                                                       374 non-null    float64
 61  Unnamed: 61                                                                                       374 non-null    float64
 62  Unnamed: 62                                                                                       374 non-null    float64
 63  Unnamed: 63                                                                                       374 non-null    float64
 64  Unnamed: 64                                                                                       374 non-null    float64
 65  Unnamed: 65                                                                                       374 non-null    float64
 66  Unnamed: 66                                                                                       374 non-null    float64
 67  Unnamed: 67                                                                                       374 non-null    float64
 68  Unnamed: 68                                                                                       374 non-null    float64
 69  Unnamed: 69                                                                                       374 non-null    float64
 70  Unnamed: 70                                                                                       374 non-null    float64
 71  Unnamed: 71                                                                                       374 non-null    float64
 72  Unnamed: 72                                                                                       374 non-null    float64
 73  Unnamed: 73                                                                                       374 non-null    float64
 74  Unnamed: 74                                                                                       374 non-null    float64
 75  Unnamed: 75                                                                                       374 non-null    float64
 76  Unnamed: 76                                                                                       374 non-null    float64
 77  Unnamed: 77                                                                                       374 non-null    float64
 78  Unnamed: 78                                                                                       374 non-null    float64
 79  Unnamed: 79                                                                                       374 non-null    float64
 80  Unnamed: 80                                                                                       374 non-null    float64
 81  Unnamed: 81                                                                                       374 non-null    float64
 82  Unnamed: 82                                                                                       374 non-null    float64
 83  Unnamed: 83                                                                                       374 non-null    float64
 84  Unnamed: 84                                                                                       374 non-null    float64
 85  Unnamed: 85                                                                                       374 non-null    float64
 86  Unnamed: 86                                                                                       374 non-null    float64
 87  Unnamed: 87                                                                                       374 non-null    float64
 88  Unnamed: 88                                                                                       374 non-null    float64
 89  Unnamed: 89                                                                                       374 non-null    float64
 90  Unnamed: 90                                                                                       374 non-null    float64
 91  Unnamed: 91                                                                                       374 non-null    float64
 92  Unnamed: 92                                                                                       374 non-null    float64
 93  Unnamed: 93                                                                                       374 non-null    float64
 94  Unnamed: 94                                                                                       374 non-null    object
dtypes: float64(90), object(5)
memory usage: 282.2+ KB

In [1039]:
df_population.columns.tolist()

['MYE2: Persons by single year of age and sex for local authorities in England and Wales, mid-2022',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Unnamed: 64',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Unnamed: 68',
 'Unnamed: 69',
 'Unnamed: 70',
 'Unnamed: 71',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Unnamed: 84',
 'Unnamed: 85',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Unnamed: 92',
 'Unnamed: 93',
 'Unnamed: 94']

In [1040]:
pd.read_excel(
    "../data/raw/ons_population_2022.xlsx",
    sheet_name="MYE2 - Persons",
    header=None
).head(20)

,0,1,2,3,4,5,6,7,8,9,...,85,86,87,88,89,90,91,92,93,94
0,MYE2: Persons by single year of age and sex fo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains one table. Freeze pane...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,To turn off freeze panes select the 'View' rib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Please choose from the links presented in the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"This met my needs, please produce it next year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,I need something slightly different (please sp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,This is not what I need at all (please specify),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Code,Name,Geography,All ages,0.0,1.0,2.0,3.0,4.0,5.0,...,81.0,82.0,83.0,84.0,85.0,86.0,87.0,88.0,89.0,90+
8,K04000001,ENGLAND AND WALES,Country,60245218,625650.0,621523.0,645257.0,657741.0,667715.0,684110.0,...,305686.0,306573.0,292338.0,271154.0,244340.0,217388.0,192039.0,163683.0,141678.0,550829
9,E92000001,ENGLAND,Country,57112542,596389.0,592815.0,614824.0,626355.0,634992.0,650699.0,...,286765.0,288663.0,275634.0,255629.0,230385.0,204955.0,181182.0,154365.0,133635.0,520326
10,E12000001,NORTH EAST,Region,2682069,25452.0,25519.0,26215.0,27519.0,28099.0,29196.0,...,14629.0,14674.0,13958.0,13030.0,11852.0,10070.0,9142.0,7584.0,6515.0,23684
11,E06000047,County Durham,Unitary Authority,527704,4642.0,4688.0,4875.0,5007.0,5121.0,5279.0,...,3123.0,2996.0,2787.0,2612.0,2442.0,2029.0,1816.0,1519.0,1293.0,4377
12,E06000005,Darlington,Unitary Authority,109413,1074.0,1068.0,1115.0,1127.0,1185.0,1127.0,...,639.0,644.0,609.0,552.0,486.0,416.0,404.0,310.0,303.0,1034
13,E06000001,Hartlepool,Unitary Authority,93847,900.0,944.0,1017.0,1035.0,1016.0,1118.0,...,466.0,488.0,447.0,462.0,430.0,314.0,325.0,259.0,220.0,790
14,E06000002,Middlesbrough,Unitary Authority,148583,1782.0,1707.0,1772.0,1848.0,1889.0,2012.0,...,630.0,626.0,603.0,575.0,501.0,475.0,394.0,338.0,296.0,1087
15,E06000057,Northumberland,Unitary Authority,324286,2555.0,2741.0,2694.0,2901.0,3070.0,3160.0,...,2186.0,2149.0,2027.0,1843.0,1733.0,1497.0,1336.0,1077.0,924.0,3539
16,E06000003,Redcar and Cleveland,Unitary Authority,137168,1322.0,1192.0,1326.0,1379.0,1413.0,1525.0,...,905.0,907.0,896.0,760.0,727.0,614.0,514.0,432.0,360.0,1354
17,E06000004,Stockton-on-Tees,Unitary Authority,200112,1965.0,1942.0,2141.0,2214.0,2238.0,2419.0,...,1051.0,1004.0,943.0,897.0,771.0,650.0,610.0,477.0,402.0,1584
18,E11000007,Tyne and Wear (Met County),Metropolitan County,1140956,11212.0,11237.0,11275.0,12008.0,12167.0,12556.0,...,5629.0,5860.0,5646.0,5329.0,4762.0,4075.0,3743.0,3172.0,2717.0,9919
19,E08000037,Gateshead,Metropolitan District,197922,1929.0,1947.0,1950.0,2043.0,2052.0,2237.0,...,1131.0,1134.0,1168.0,1027.0,923.0,735.0,725.0,617.0,564.0,1802

In [1041]:
df_population = pd.read_excel(
    "../data/raw/ons_population_2022.xlsx",
    sheet_name="MYE2 - Persons",
    header=7
)

df_population.head()

,Code,Name,Geography,All ages,0,1,2,3,4,5,...,81,82,83,84,85,86,87,88,89,90+
0,K04000001,ENGLAND AND WALES,Country,60245218,625650,621523,645257,657741,667715,684110,...,305686,306573,292338,271154,244340,217388,192039,163683,141678,550829
1,E92000001,ENGLAND,Country,57112542,596389,592815,614824,626355,634992,650699,...,286765,288663,275634,255629,230385,204955,181182,154365,133635,520326
2,E12000001,NORTH EAST,Region,2682069,25452,25519,26215,27519,28099,29196,...,14629,14674,13958,13030,11852,10070,9142,7584,6515,23684
3,E06000047,County Durham,Unitary Authority,527704,4642,4688,4875,5007,5121,5279,...,3123,2996,2787,2612,2442,2029,1816,1519,1293,4377
4,E06000005,Darlington,Unitary Authority,109413,1074,1068,1115,1127,1185,1127,...,639,644,609,552,486,416,404,310,303,1034

In [1042]:
df_population["Geography"].unique()

array(['Country', 'Region', 'Unitary Authority', 'Metropolitan County',
       'Metropolitan District', 'County', 'Non-metropolitan District',
       'London Borough'], dtype=object)

In [1043]:
df_london_population = df_population[
    df_population["Geography"] == "London Borough"
]

df_london_population.head()

,Code,Name,Geography,All ages,0,1,2,3,4,5,...,81,82,83,84,85,86,87,88,89,90+
212,E09000007,Camden,London Borough,217365,2182,2103,1992,1913,1935,1967,...,659,689,609,597,474,445,391,304,279,1182
213,E09000001,City of London,London Borough,11457,76,52,41,44,41,57,...,36,41,27,34,15,24,13,16,8,43
214,E09000012,Hackney,London Borough,261632,3636,3419,3180,3065,2900,2962,...,502,479,430,382,352,361,316,233,223,762
215,E09000013,Hammersmith and Fulham,London Borough,185506,2053,1948,1754,1772,1661,1788,...,543,547,516,415,371,340,272,253,212,777
216,E09000014,Haringey,London Borough,262413,3244,3063,2990,2881,2873,2776,...,704,721,671,663,548,537,425,403,298,1138

In [1044]:
df_london_population.shape

(33, 95)

In [1045]:
df_london_population["Name"]

212                    Camden
213            City of London
214                   Hackney
215    Hammersmith and Fulham
216                  Haringey
217                 Islington
218    Kensington and Chelsea
219                   Lambeth
220                  Lewisham
221                    Newham
222                 Southwark
223             Tower Hamlets
224                Wandsworth
225               Westminster
226      Barking and Dagenham
227                    Barnet
228                    Bexley
229                     Brent
230                   Bromley
231                   Croydon
232                    Ealing
233                   Enfield
234                 Greenwich
235                    Harrow
236                  Havering
237                Hillingdon
238                  Hounslow
239      Kingston upon Thames
240                    Merton
241                 Redbridge
242      Richmond upon Thames
243                    Sutton
244            Waltham Forest
Name: Name, dtype: object

In [1046]:
df_london_population_clean = df_london_population[
    ["Code", "Name", "Geography", "All ages"]
]

df_london_population_clean.head()

          Code                    Name       Geography  All ages
212  E09000007                  Camden  London Borough    217365
213  E09000001          City of London  London Borough     11457
214  E09000012                 Hackney  London Borough    261632
215  E09000013  Hammersmith and Fulham  London Borough    185506
216  E09000014                Haringey  London Borough    262413

In [1047]:
df_london_population_clean = df_london_population_clean.rename(
    columns={
        "Code": "borough_code",
        "Name": "borough_name",
        "Geography": "geography",
        "All ages": "population"
    }
)

df_london_population_clean.head()

    borough_code            borough_name       geography  population
212    E09000007                  Camden  London Borough      217365
213    E09000001          City of London  London Borough       11457
214    E09000012                 Hackney  London Borough      261632
215    E09000013  Hammersmith and Fulham  London Borough      185506
216    E09000014                Haringey  London Borough      262413

In [1048]:
df_london_population_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 212 to 244
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   borough_code  33 non-null     object
 1   borough_name  33 non-null     object
 2   geography     33 non-null     object
 3   population    33 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

In [1049]:
df_london_population_clean.describe()

          population
count      33.000000
mean   268758.878788
std     78722.017731
min     11457.000000
25%    217365.000000
50%    276312.000000
75%    323854.000000
max    392610.000000

In [1050]:
import pandas as pd

df_area = pd.read_csv("../data/raw/london_borough_area.csv")

In [1051]:
df_area.head()

,Code,Name,Year,Source,Population,Inland_Area _Hectares,Total_Area_Hectares,Population_per_hectare,Square_Kilometres,Population_per_square_kilometre
0,E09000001,City of London,1999,ONS MYE,6581,290.4,314.9,22.7,2.9,2266.2
1,E09000001,City of London,2000,ONS MYE,7014,290.4,314.9,24.2,2.9,2415.3
2,E09000001,City of London,2001,ONS MYE,7359,290.4,314.9,25.3,2.9,2534.1
3,E09000001,City of London,2002,ONS MYE,7280,290.4,314.9,25.1,2.9,2506.9
4,E09000001,City of London,2003,ONS MYE,7115,290.4,314.9,24.5,2.9,2450.1

In [1052]:
df_area.shape

(1872, 10)

In [1053]:
df_area.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Code                             1872 non-null   object
 1   Name                             1872 non-null   object
 2   Year                             1872 non-null   int64
 3   Source                           1872 non-null   object
 4   Population                       1872 non-null   int64
 5   Inland_Area _Hectares            1872 non-null   float64
 6   Total_Area_Hectares              1872 non-null   float64
 7   Population_per_hectare           1872 non-null   float64
 8   Square_Kilometres                1872 non-null   float64
 9   Population_per_square_kilometre  1872 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 146.4+ KB

In [1054]:
df_area["Year"].unique()

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031,
       2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042,
       2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050])

In [1055]:
df_area[df_area["Year"] == 2025].head()

,Code,Name,Year,Source,Population,Inland_Area _Hectares,Total_Area_Hectares,Population_per_hectare,Square_Kilometres,Population_per_square_kilometre
26,E09000001,City of London,2025,GLA Population Projections,8661,290.4,314.9,29.8,2.9,2982.5
78,E09000002,Barking and Dagenham,2025,GLA Population Projections,234317,3610.8,3779.9,64.9,36.1,6489.4
130,E09000003,Barnet,2025,GLA Population Projections,422894,8674.8,8674.8,48.7,86.7,4875.0
182,E09000004,Bexley,2025,GLA Population Projections,265249,6058.1,6428.6,43.8,60.6,4378.4
234,E09000005,Brent,2025,GLA Population Projections,358170,4323.3,4323.3,82.8,43.2,8284.7

In [1056]:
df_area[df_area["Year"] == 2025].shape

(36, 10)

In [1057]:
df_area[df_area["Year"] == 2025]["Name"]

26              City of London
78        Barking and Dagenham
130                     Barnet
182                     Bexley
234                      Brent
286                    Bromley
338                     Camden
390                    Croydon
442                     Ealing
494                    Enfield
546                  Greenwich
598                    Hackney
650     Hammersmith and Fulham
702                   Haringey
754                     Harrow
806                   Havering
858                 Hillingdon
910                   Hounslow
962                  Islington
1014    Kensington and Chelsea
1066      Kingston upon Thames
1118                   Lambeth
1170                  Lewisham
1222                    Merton
1274                    Newham
1326                 Redbridge
1378      Richmond upon Thames
1430                 Southwark
1482                    Sutton
1534             Tower Hamlets
1586            Waltham Forest
1638                Wandsworth
1690               Westminster
1742            Greater London
1794              Inner London
1846              Outer London
Name: Name, dtype: object

In [1058]:
df_area_2025 = df_area[df_area["Year"] == 2025]

df_area_clean = df_area_2025[
    df_area_2025["Name"].isin(df_london_population_clean["borough_name"])
]

df_area_clean.shape

(33, 10)

In [1059]:
df_area_clean = df_area_clean[
    ["Code", "Name", "Square_Kilometres"]
]

df_area_clean.head()

          Code                  Name  Square_Kilometres
26   E09000001        City of London                2.9
78   E09000002  Barking and Dagenham               36.1
130  E09000003                Barnet               86.7
182  E09000004                Bexley               60.6
234  E09000005                 Brent               43.2

In [1060]:
df_area_clean = df_area_clean.rename(
    columns={
        "Code": "borough_code",
        "Name": "borough_name",
        "Square_Kilometres": "area_sq_km"
    }
)

df_area_clean.head()

    borough_code          borough_name  area_sq_km
26     E09000001        City of London         2.9
78     E09000002  Barking and Dagenham        36.1
130    E09000003                Barnet        86.7
182    E09000004                Bexley        60.6
234    E09000005                 Brent        43.2

In [1061]:
df_area_clean.shape

(33, 3)

In [1062]:
df_area_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 26 to 1690
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   borough_code  33 non-null     object
 1   borough_name  33 non-null     object
 2   area_sq_km    33 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.0+ KB

In [1063]:
df_area_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 26 to 1690
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   borough_code  33 non-null     object
 1   borough_name  33 non-null     object
 2   area_sq_km    33 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.0+ KB

In [1064]:
df_area_clean.isnull().sum()

borough_code    0
borough_name    0
area_sq_km      0
dtype: int64

In [1065]:
df_area_clean.duplicated().sum()

np.int64(0)

In [1066]:
df_area_clean["borough_name"].nunique()

33

In [1067]:
df_area_clean["borough_code"].nunique()

33

In [1068]:
df_borough_master = df_london_population_clean.merge(
    df_area_clean,
    on="borough_name",
    how="inner"
)

In [1069]:
df_borough_master.shape

(33, 6)

In [1070]:
df_borough_master.head()

,borough_code_x,borough_name,geography,population,borough_code_y,area_sq_km
0,E09000007,Camden,London Borough,217365,E09000007,21.8
1,E09000001,City of London,London Borough,11457,E09000001,2.9
2,E09000012,Hackney,London Borough,261632,E09000012,19.0
3,E09000013,Hammersmith and Fulham,London Borough,185506,E09000013,16.4
4,E09000014,Haringey,London Borough,262413,E09000014,29.6

In [1071]:
(df_borough_master["borough_code_x"] ==
 df_borough_master["borough_code_y"]).all()

np.True_

In [1072]:
df_borough_master["population_density"] = (
    df_borough_master["population"] /
    df_borough_master["area_sq_km"]
)

In [1073]:
df_borough_master.head()

,borough_code_x,borough_name,geography,population,borough_code_y,area_sq_km,population_density
0,E09000007,Camden,London Borough,217365,E09000007,21.8,9970.871560
1,E09000001,City of London,London Borough,11457,E09000001,2.9,3950.689655
2,E09000012,Hackney,London Borough,261632,E09000012,19.0,13770.105263
3,E09000013,Hammersmith and Fulham,London Borough,185506,E09000013,16.4,11311.341463
4,E09000014,Haringey,London Borough,262413,E09000014,29.6,8865.304054

In [1074]:
df_borough_master = (
    df_borough_master
    .drop(columns=["borough_code_y"])
    .rename(columns={"borough_code_x": "borough_code"})
)

In [1075]:
df_borough_master.head()

,borough_code,borough_name,geography,population,area_sq_km,population_density
0,E09000007,Camden,London Borough,217365,21.8,9970.871560
1,E09000001,City of London,London Borough,11457,2.9,3950.689655
2,E09000012,Hackney,London Borough,261632,19.0,13770.105263
3,E09000013,Hammersmith and Fulham,London Borough,185506,16.4,11311.341463
4,E09000014,Haringey,London Borough,262413,29.6,8865.304054

In [1076]:
df_borough_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   borough_code        33 non-null     object
 1   borough_name        33 non-null     object
 2   geography           33 non-null     object
 3   population          33 non-null     int64
 4   area_sq_km          33 non-null     float64
 5   population_density  33 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.7+ KB

In [1077]:
df_borough_master.sort_values(
    "population_density",
    ascending=False
).head(10)

,borough_code,borough_name,geography,population,area_sq_km,population_density
11,E09000030,Tower Hamlets,London Borough,323854,19.8,16356.262626
5,E09000019,Islington,London Borough,219594,14.9,14737.852349
2,E09000012,Hackney,London Borough,261632,19.0,13770.105263
6,E09000020,Kensington and Chelsea,London Borough,146392,12.1,12098.512397
7,E09000022,Lambeth,London Borough,316700,26.8,11817.164179
3,E09000013,Hammersmith and Fulham,London Borough,185506,16.4,11311.341463
10,E09000028,Southwark,London Borough,311492,28.9,10778.269896
0,E09000007,Camden,London Borough,217365,21.8,9970.871560
9,E09000025,Newham,London Borough,357147,36.2,9865.939227
13,E09000033,Westminster,London Borough,209866,21.5,9761.209302

In [1078]:
import pandas as pd

xls = pd.ExcelFile("../data/raw/ons_population_2022.xlsx")

print(xls.sheet_names)

['Cover sheet', 'Contents', 'Notes', 'Geography guide', 'Related publications', 'MYE1', 'MYE2 - Persons', 'MYE2 - Females', 'MYE2 - Males', 'MYE3', 'MYE4', 'MYE5', 'MYE6']

In [1079]:
mye4 = pd.read_excel(
    population_file,
    sheet_name="MYE4"
)

NameError: name 'population_file' is not defined